version: "3.8"

services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    volumes:
      - $HOME/neo4j/data:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: "none"
